#!/bin/bash
#
# Test Runner Script for viterby-site
# Runs all quality checks and updates TEST_STATUS.md
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Project root directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
STATUS_FILE="$PROJECT_ROOT/tests/TEST_STATUS.md"

# Timestamp
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
DATE_ONLY=$(date '+%Y-%m-%d')

# Results tracking
LINT_STATUS="FAIL"
LINT_OUTPUT=""
TYPE_STATUS="FAIL"
TYPE_OUTPUT=""
BUILD_STATUS="FAIL"
BUILD_OUTPUT=""
UNIT_STATUS="NOT CONFIGURED"
E2E_STATUS="NOT CONFIGURED"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  viterby-site Test Runner${NC}"
echo -e "${BLUE}  $TIMESTAMP${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

cd "$PROJECT_ROOT"

# 1. Lint Check
echo -e "${YELLOW}[1/4] Running Lint Check...${NC}"
# Note: Using npm run lint which properly invokes eslint with flat config
if LINT_OUTPUT=$(npm run lint 2>&1); then
    LINT_STATUS="PASS"
    echo -e "${GREEN}  Lint: PASS${NC}"
else
    LINT_STATUS="FAIL"
    echo -e "${RED}  Lint: FAIL${NC}"
    echo "$LINT_OUTPUT"
fi
echo ""

# 2. Type Check
echo -e "${YELLOW}[2/4] Running Type Check...${NC}"
if TYPE_OUTPUT=$(npx tsc --noEmit 2>&1); then
    TYPE_STATUS="PASS"
    echo -e "${GREEN}  Type Check: PASS${NC}"
else
    TYPE_STATUS="FAIL"
    echo -e "${RED}  Type Check: FAIL${NC}"
    echo "$TYPE_OUTPUT"
fi
echo ""

# 3. Unit Tests (when configured)
echo -e "${YELLOW}[3/4] Running Unit Tests...${NC}"
if [ -f "$PROJECT_ROOT/vitest.config.ts" ] || [ -f "$PROJECT_ROOT/vitest.config.js" ]; then
    if UNIT_OUTPUT=$(npm run test 2>&1); then
        UNIT_STATUS="PASS"
        echo -e "${GREEN}  Unit Tests: PASS${NC}"
    else
        UNIT_STATUS="FAIL"
        echo -e "${RED}  Unit Tests: FAIL${NC}"
        echo "$UNIT_OUTPUT"
    fi
else
    echo -e "${YELLOW}  Unit Tests: NOT CONFIGURED (Vitest will be set up in Prompt 5)${NC}"
fi
echo ""

# 4. Build Check
echo -e "${YELLOW}[4/4] Running Build...${NC}"
if BUILD_OUTPUT=$(npm run build 2>&1); then
    BUILD_STATUS="PASS"
    echo -e "${GREEN}  Build: PASS${NC}"
else
    BUILD_STATUS="FAIL"
    echo -e "${RED}  Build: FAIL${NC}"
    echo "$BUILD_OUTPUT"
fi
echo ""

# Get git status
GIT_STATUS=$(git status --short 2>/dev/null || echo "Not a git repository")

# Summary
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Summary${NC}"
echo -e "${BLUE}========================================${NC}"
echo -e "  Lint:       ${LINT_STATUS}"
echo -e "  Type Check: ${TYPE_STATUS}"
echo -e "  Unit Tests: ${UNIT_STATUS}"
echo -e "  Build:      ${BUILD_STATUS}"
echo ""

# Determine overall status
if [ "$LINT_STATUS" = "PASS" ] && [ "$TYPE_STATUS" = "PASS" ] && [ "$BUILD_STATUS" = "PASS" ]; then
    if [ "$UNIT_STATUS" = "NOT CONFIGURED" ] || [ "$UNIT_STATUS" = "PASS" ]; then
        OVERALL="PASS"
        echo -e "${GREEN}  Overall: ALL CHECKS PASSED${NC}"
    else
        OVERALL="FAIL"
        echo -e "${RED}  Overall: SOME CHECKS FAILED${NC}"
    fi
else
    OVERALL="FAIL"
    echo -e "${RED}  Overall: SOME CHECKS FAILED${NC}"
fi
echo ""

# Update TEST_STATUS.md
cat > "$STATUS_FILE" << EOF
# Test Status Report

> Auto-generated by the QA agent. Last updated: $TIMESTAMP

## Summary

| Check | Status | Details |
|-------|--------|---------|
| Build | $BUILD_STATUS | Next.js 16.1.6 (Turbopack) |
| Lint | $LINT_STATUS | ESLint |
| Type Check | $TYPE_STATUS | TypeScript |
| Unit Tests | $UNIT_STATUS | Vitest (when configured) |
| E2E Tests | $E2E_STATUS | Playwright (when configured) |

## Build Status

- **Status**: $BUILD_STATUS
- **Last Run**: $TIMESTAMP
- **Framework**: Next.js 16.1.6 (Turbopack)

## Lint Status

- **Status**: $LINT_STATUS
- **Last Run**: $TIMESTAMP
- **Tool**: ESLint 9.x

## Type Check Status

- **Status**: $TYPE_STATUS
- **Last Run**: $TIMESTAMP
- **Tool**: TypeScript 5.x

## Coverage Metrics

Coverage reporting will be available once Vitest is configured (Prompt 5).

| Metric | Value |
|--------|-------|
| Statements | N/A |
| Branches | N/A |
| Functions | N/A |
| Lines | N/A |

## Test Results

### Unit Tests
$UNIT_STATUS - Will be set up with Vitest in Prompt 5.

### E2E Tests
$E2E_STATUS - Will be set up with Playwright in Prompt 5.

## Git Status

\`\`\`
$GIT_STATUS
\`\`\`

## History

| Date | Build | Lint | Type Check | Unit Tests | E2E Tests |
|------|-------|------|------------|------------|-----------|
| $DATE_ONLY | $BUILD_STATUS | $LINT_STATUS | $TYPE_STATUS | $UNIT_STATUS | $E2E_STATUS |

---

## How to Use

Run the test runner script to update this status:
\`\`\`bash
./scripts/run-tests.sh
\`\`\`

Or run individual checks:
\`\`\`bash
npm run lint          # Lint check
npx tsc --noEmit      # Type check
npm run build         # Build check
\`\`\`
EOF

echo -e "${GREEN}TEST_STATUS.md updated at: $STATUS_FILE${NC}"
echo ""

# Exit with appropriate code
if [ "$OVERALL" = "PASS" ]; then
    exit 0
else
    exit 1
fi
